<?php
/**
 * @var $block \IWD\AuthCIM\Block\Customer\Edit\Tab\Cards\Form
 */

$cards = $block->getSavedCcList();
?>

<ul class="profile-list block">
    <?php /* @escapeNotVerified */ echo $block->getChildHtml('iwd.authcim.edit.tab.cards.list.before') ?>

    <?php foreach ($cards as $card) : ?>
        <?php
        $isAllowedCcType = $block->isAllowedCcType($card);
        $isInUse = $card->isInUse();
        $expired = $card->isExpired();
        $id = $card->getId();
        ?>

        <li class="profile-list-item iwd-cim-card-list-item" data-id="<?php /* @escapeNotVerified */ echo $card->getHash() ?>">
            <div class="profile-list-item-actions actions">
                <button class="action-delete" type="button" title="<?php /* @escapeNotVerified */ echo __('Delete Saved Card'); ?>">
                    <i class="fa fa-times-circle"></i>
                </button>
                <button class="action-cancel-delete" type="button">
                    <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                </button>
                <button class="action-delete-2" type="button">
                    <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                </button>
            </div>

            <div class="card-info">
                <div class="cc-number"><?php /* @escapeNotVerified */ echo $card->getLastCreditCardNumber() ?></div>
                <div class="labels">
                    <?php if ($isInUse && $isAllowedCcType) : ?>
                        <div class="label is_in_use"
                             tooltip="<?php /* @escapeNotVerified */ echo __('This card associated with order(s).'); ?>">
                            <i class="fa fa-check-circle"></i>&nbsp;<span class="title"><?php /* @escapeNotVerified */ echo __('In Use'); ?></span>
                        </div>
                    <?php endif; ?>
                    <?php if (!$isAllowedCcType) : ?>
                        <div class="label disallow"
                             tooltip="<?php /* @escapeNotVerified */ echo __('Credit card type is not allowed for use.'); ?>">
                            <i class="fa fa-exclamation-circle"></i>&nbsp;<span class="title"><?php /* @escapeNotVerified */ echo __('Not Supported'); ?></span>
                        </div>
                    <?php endif; ?>
                    <?php if ($expired) : ?>
                        <div class="label disallow"
                             tooltip="<?php /* @escapeNotVerified */ echo __('This card is expired data.'); ?>">
                            <i class="fa fa-exclamation-circle"></i>&nbsp;<span class="title"><?php /* @escapeNotVerified */ echo __('Expired'); ?></span>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="clear"></div>
            </div>
            <div class="cc-expiration-date"><?php /* @escapeNotVerified */ echo $card->getExpirationDate(true) ?></div>
            <div class="cc-type"><?php /* @escapeNotVerified */ echo $card->getCreditCardType() ?></div>

            <address>
                <?php /* @escapeNotVerified */ echo $block->getAddressHtml($card) ?>
            </address>

            <div class="actions bottom-actions">
                <button class="action-edit" type="button">
                    <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
                </button>
                <button class="action-cancel iwd_cim_cancel_save_cc" type="button">
                    <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                </button>
                <button class="action-save iwd_cim_save_cc" type="button">
                    <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
                </button>
                <div class="clear"></div>
            </div>
        </li>
    <?php endforeach; ?>

    <li class="profile-list-actions last">
        <button class="action primary add" type="button" id="iwd_cim_add_cc">
            <span><?php /* @escapeNotVerified */ echo __('Add New Card') ?></span>
        </button>
        <script>
            window.iwdAuthcimCards = <?php /* @escapeNotVerified */ echo $block->getCardsList(); ?>
        </script>
    </li>
</ul>