<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<div class="cart-totals">
    <div class="table-wrapper">
        <table id="shopping-cart-totals-table" class="data table totals">
            <caption class="table-caption"><?php echo __('Total'); ?></caption>
            <?php echo $block->getChildHtml('rewardpoints')?>
            <?php echo $block->renderTotals(); ?>
            <?php echo $block->getChildHtml('redeempoints')?>
            <?php echo $block->getChildHtml('credit')?>
            <?php echo $block->getChildHtml('rewardpoints_totals')?>
            <tfoot>
            	<?php echo $block->renderTotals('footer'); ?>
            </tfoot>
        </table>
    </div>
</div>
<div id="shopping-cart-totals-please-wait" style="display: none;">
	<div style="text-align:center;margin-top:30px;">
	    <img src="<?php echo $block->getViewFileUrl('MW_RewardPoints::images/loading.gif')?>" class="v-middle" alt="loading"> &nbsp;
	    <?php echo __("Updating cart information...")?>
	</div>
</div>
