<div class="table-wrapper">
    <table id="shopping-cart-totals-table" class="data table totals">
        <caption class="table-caption"><?php echo __('Total'); ?></caption>
        <?php echo $block->getChildHtml('rewardpoints')?>
        <?php echo $block->renderTotals(); ?>
        <?php echo $block->getChildHtml('redeempoints')?>
        <?php echo $block->getChildHtml('credit')?>
        <?php echo $block->getChildHtml('rewardpoints_totals')?>
        <tfoot>
        	<?php echo $block->renderTotals('footer'); ?>
        </tfoot>
    </table>
</div>