<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/** @var $block \Aheadworks\Rma\Block\Adminhtml\CustomField\Edit\Form\Element\Renderer\Options */
?>
<div id="manage-options-panel" data-visible="type">
    <table class="admin__control-table">
        <thead>
            <tr id="custom-field-options-table">
                <th class="col-draggable"></th>
                <th class="col-default control-table-actions-th"><?php echo __('Is Default') ?></th>
                <th class="col-default control-table-actions-th" <?php if (!$block->allowDisableOption()): ?>style="display: none;"<?php endif; ?>><?php echo __('Enabled') ?></th>
                <?php foreach ($block->getStores() as $store): ?>
                        <th><?php echo __($store->getName()) ?></th>
                <?php endforeach;
                    $storeTotal = count($block->getStores()) + 4;
                ?>
                <th class="col-delete">&nbsp;</th>
            </tr>
        </thead>
        <tbody data-role="options-container" class="ignore-validate"></tbody>
        <tfoot>
            <tr>
                <th colspan="<?php echo $storeTotal; ?>" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry" name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <?php if ($block->allowAddOption()): ?>
                <tr>
                    <th colspan="<?php echo $storeTotal; ?>" class="col-actions-add">
                            <button id="add_new_option_button" title="<?php echo __('Add Option'); ?>"
                                    type="button" class="action- scalable add">
                                <span><?php echo __('Add Option'); ?></span>
                            </button>
                    </th>
                </tr>
            <?php endif; ?>
        </tfoot>
    </table>
    <input type="hidden" id="option-count-check" value="" />
</div>

<script id="row-template" type="text/x-magento-template">
    <tr>
        <td class="col-draggable">
            <div data-role="draggable-handle" class="draggable-handle" title="<?php echo __('Sort Option'); ?>"></div>
            <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>"/>
        </td>
        <td class="col-default control-table-actions-cell">
            <input class="input-radio" type="<%- data.intype %>" name="option[default][]" value="<%- data.id %>" <%- data.checked %>/>
        </td>
        <td class="col-default control-table-actions-cell" <?php if (!$block->allowDisableOption()): ?>style="display: none;"<?php endif; ?>>
            <input class="input-checkbox" type="checkbox" name="option[enable][]" value="<%- data.id %>" <%- data.enable %>/>
        </td>
            <?php foreach ($block->getStores() as $store): ?>
                <td class="col-<%- data.id %>">
                    <input name="option[value][<%- data.id %>][<?php echo $store->getId() ?>]"
                           value="<%- data.store<?php echo $store->getId() ?> %>"
                           class="input-text<?php if ($store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>"
                           type="text"
                        />
                </td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
        <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                    <button id="delete_button_<%- data.id %>"
                            title="<?php echo __('Delete') ?>"
                            type="button"
                            style="display: none;"
                            class="action- scalable delete delete-option"
                        >
                        <span><?php echo __('Delete') ?></span>
                    </button>
            </td>
    </tr>
</script>
<?php echo $block->getInitJs(); ?>
