<?php
/**
 * @var $block IWD\MultiInventory\Block\Adminhtml\Warehouses\Jsinit
 */
?>

<script type="text/javascript">
    // <![CDATA[
    require([
            "IWD_MultiInventory/js/order/view/warehouse",
            "prototype"
        ],
        function (iwdMultiInventoryOrderViewWarehouse) {
            var multiInventoryOrderViewWarehouse = new iwdMultiInventoryOrderViewWarehouse();
            multiInventoryOrderViewWarehouse.init(<?php echo $block->jsonParamsOrderViewWarehouse(); ?>);
        }
    );
    // ]]>
</script>