<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/** @var \Aheadworks\Helpdesk\Block\Customer\TicketCreate $block */
?>
<form class="form form-create-ticket" action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>" method="post" id="form-validate">
    <fieldset class="fieldset">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Create New Ticket') ?></span></legend><br>
        <div class="field subject required">
            <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject') ?></span></label>
            <div class="control">
                <input type="text" id="subject" name="subject" title="<?php /* @escapeNotVerified */ echo __('Subject') ?>" class="input-text">
            </div>
        </div>
        <?php if ($block->getDepartments()) :?>
        <div class="field department_id required">
            <label for="department_id" class="label"><span><?php /* @escapeNotVerified */ echo __('Department') ?></span></label>
            <div class="control">
                <select id="department_id" name="department_id">
                    <?php foreach ($block->getDepartments() as $departmentId => $name): ?>
                        <option value="<?php echo $block->escapeHtml($departmentId); ?>">
                            <?php echo $block->escapeHtml($name); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <?php endif; ?>
        <div class="field order_id">
            <label for="order_id" class="label"><span><?php /* @escapeNotVerified */ echo __('Order') ?></span></label>
            <div class="control">
                <select id="order_id" name="order_id">
                    <option value=""><?php echo $block->escapeHtml(__('Unassigned'));?></option>
                    <?php foreach ($block->getOrdersAsOptionArray() as $orderId => $incrementId): ?>
                        <option
                            value="<?php echo $block->escapeHtml($orderId); ?>"
                            <?php echo $block->isPreselectedOrder($orderId) ? "selected='selected'" : ""?> >
                            <?php echo $block->escapeHtml($incrementId); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field content required">
            <label class="label" for="content"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
            <div class="control">
                <textarea id="content" name="content" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div>
        <div class="field attachment">
            <label class="label" for="attachment"><span><?php /* @escapeNotVerified */ echo __('Attachments') ?></span></label>
            <div class="control">
                <?php echo $block->getChildHtml('fileUpload') ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary"><button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit Ticket') ?>" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit Ticket') ?></span></button></div>
    </div>
</form>
