<?php

/**
 * @var \IWD\OrderManager\Model\Order\Item $item
 * @var \Magento\CatalogInventory\Api\Data\StockItemInterface $stock
 */

$item       = $block->getOrderItem();
$id         = $block->getOrderItemId();
$type       = $block->getEditedItemType();
$hasParent  = $block->hasOrderItemParent();
$parentId   = $block->getParentItemId();

$stock      = $block->getStockObjectForOrderItem();
$stockQty   = $block->getStockQty();
$itemQty    = $block->getItemQty();

$stockQtyIncrements = $stock->getQtyIncrements();
$canShowPriceInfo   = $block->canShowPriceInfo($item);

$canEditItem = $block->isAllowedAction('items_edit');
$canDeleteItem = $block->isAllowedAction('items_delete');
?>

<tr class="headings <?php if($hasParent): ?>has-parent<?php endif; ?> type-<?php echo $type?>"
    <?php if($hasParent): ?>data-parent-id="<?php echo $parentId ?>"<?php endif; ?>
    data-item-id="<?php echo $id ?>">

    <?php /** NAME / SKU **/ ?>
    <td class="col-product">
        <div>
            <div class="product-title"><?php echo $item->getName() ?></div>
            <div class="product-sku-block"><span><?php echo __("SKU") ?>: </span><?php echo $item->getSku() ?></div>
        </div>
        <?php if($canEditItem): ?>
            <input type="text" name="item[<?php echo $id ?>][description]"
               placeholder="<?php echo __('Description') ?>"
               title="<?php echo __("Description") ?>"
               class="edit_order_item large"
               value="<?php echo $item->getDescription() ?>"/>
        <?php endif; ?>
        <?php if($item->getHasError() && $item->getMessage()): ?>
            <div class="notice">
                <?php echo $item->getMessage(); ?>
            </div>
        <?php endif; ?>
    </td>


    <?php /** STATUS **/ ?>
    <td class="col-status">
        <?php if($canShowPriceInfo): ?>
            <?php if($type == 'quote'): ?>
                <?php echo __('Added') ?>
            <?php else: ?>
                <?php echo $item->getStatus() ?>
            <?php endif; ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>


    <?php /** ORIGINAL PRICE **/ ?>
    <td class="col-price-original">
        <?php if($canShowPriceInfo): ?>
            <?php echo $block->displayPriceAttribute('original_price') ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>


    <?php /** PRICE **/ ?>
    <td class="col-price">
        <label ><?php echo __('Excl.Tax:') ?>&nbsp;<b><?php echo $block->getPriceHtml('price'); ?></b></label><br/>
        <?php if($canEditItem): ?>
        <input type="text" name="item[<?php echo $id ?>][price]"
               title="<?php echo __("Price") ?>"
               class="edit_order_item required-entry validate-number
               <?php if($canShowPriceInfo || $item->getQtyRefunded() > 0): ?>readonly" readonly="readonly"<?php endif; ?>
               value="<?php echo $block->getPrice('price'); ?>"/><br/>
        <?php endif; ?>

        <label ><?php echo __('Incl.Tax:') ?>&nbsp;<b><?php echo $block->getPriceHtml('price_incl_tax'); ?></b></label><br/>
        <?php if($canEditItem): ?>
        <input type="text" name="item[<?php echo $id ?>][price_incl_tax]"
               title="<?php echo __("Price includes tax") ?>"
               class="edit_order_item required-entry validate-number
               <?php if($canShowPriceInfo || $item->getQtyRefunded() > 0): ?>readonly" readonly="readonly"<?php endif; ?>
               value="<?php echo $block->getPrice('price_incl_tax'); ?>"/>
        <?php endif; ?>
    </td>


    <?php /** QTY **/ ?>
    <td class="col-ordered-qty">
        <table class="qty-table">
            <tr>
                <td><?php echo __("Ordered"); ?></td><td><?php echo $item->getQtyOrdered() * 1; ?></td>
            </tr>
            <?php if ($item->getQtyInvoiced() > 0): ?>
                <tr>
                    <td><?php echo __("Invoiced") ?></td><td><?php  echo $item->getQtyInvoiced() * 1; ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($item->getQtyRefunded() > 0): ?>
                <tr>
                    <td><?php echo __("Refunded") ?></td><td><?php  echo $item->getQtyRefunded() * 1; ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($item->getQtyShipped() > 0): ?>
                <tr>
                    <td><?php  echo __("Shipped") ?></td><td><?php  echo $item->getQtyShipped() * 1; ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($item->getQtyCanceled() > 0): ?>
                <tr>
                    <td><?php  echo __("Canceled") ?></td><td><?php  echo $item->getQtyCanceled() * 1; ?></td>
                </tr>
            <?php endif; ?>
            <?php if($canEditItem): ?>
                <tr>
                    <td><b><?php echo __("New&nbsp;qty"); ?></b></td>
                    <td>
                        <input type="text" class="edit_order_item required-entry validate-number"
                               value="<?php echo $itemQty * 1; ?>"
                               name="item[<?php echo $id; ?>][fact_qty]"
                               data-stock-validate="<?php echo $block->isStockValidation($item, $stockQty) ?>"
                               data-start-qty="<?php echo  $item->getQtyOrdered() * 1; ?>"
                               data-fact-qty="<?php echo $itemQty; ?>"
                               data-stock-qty-increment="<?php echo $stockQtyIncrements ? $stockQtyIncrements : 1 ?>"
                               data-stock-qty="<?php echo $stockQty ? $stockQty : 1 ?>"
                               data-stock-qty-min="<?php echo $stock->getMinQty() ? $stock->getMinQty() : 1 ?>"
                               data-stock-min-sales-qty="<?php echo $stock->getMinSaleQty() ? $stock->getMinSaleQty() : 1 ?>"
                               data-stock-max-sales-qty="<?php echo $stock->getMaxSaleQty() ? $stock->getMaxSaleQty() : 1 ?>"
                               data-qty-refunded="<?php echo $item->getQtyRefunded(); ?>"
                            <?php if($stockQtyIncrements): ?>
                                title="<?php echo __('Qty increments x%1', $stockQtyIncrements); ?>"
                            <?php endif; ?>
                            />
                    </td>
                </tr>
            <?php endif; ?>
        </table>
    </td>


    <?php /** SUBTOTAL **/ ?>
    <td class="col-subtotal">
        <?php echo __("Excl.Tax") ?>:&nbsp;<b><?php echo $block->getPriceHtml('base_row_total'); ?></b>
        <?php if($canEditItem): ?>
            <input type="text" readonly="readonly" class="edit_order_item required-entry validate-number readonly"
               title="<?php echo __("Subtotal") ?>"
               <?php if($canShowPriceInfo || $item->getQtyRefunded() > 0): ?>readonly="readonly"<?php endif; ?>
               value="<?php echo $block->getPrice('base_row_total'); ?>"
               name="item[<?php echo $id ?>][subtotal]"/>
        <?php endif; ?>
        <br/>

        <?php echo __("Incl.Tax") ?>:&nbsp;<b><?php echo $block->getPriceHtml('base_row_total_incl_tax'); ?></b>
        <?php if($canEditItem): ?>
            <input type="text" readonly="readonly" class="edit_order_item required-entry validate-number readonly"
               title="<?php echo __("Subtotal includes tax") ?>"
               <?php if($canShowPriceInfo || $item->getQtyRefunded() > 0): ?>readonly="readonly"<?php endif; ?>
               value="<?php echo $block->getPrice('base_row_total_incl_tax'); ?>"
               name="item[<?php echo $id ?>][subtotal_incl_tax]"/>
        <?php endif; ?>
    </td>


    <?php /** TAX AMOUNT **/ ?>
    <td class="col-tax-amount">
        <?php echo $block->getPriceHtml('tax_amount') ?>
        <?php if($canEditItem): ?>
            <input type="text" name="item[<?php echo $id ?>][tax_amount]" readonly="readonly"
               title="<?php echo __("Tax amount") ?>"
               class="edit_order_item small required-entry validate-number readonly"
               value="<?php echo $block->getPrice('base_tax_amount'); ?>"/>
        <?php endif; ?>
    </td>


    <?php /** TAX PERCENT **/ ?>
    <td class="col-tax-percent">
        <?php if ($canShowPriceInfo): ?>
            <input type="hidden" value="<?php echo $block->getPercent('tax_percent'); ?>" name="item[<?php echo $id ?>][tax_percent]"/>
        <?php else: ?>
            <label><?php echo $block->getPercentHtml('tax_percent') ?></label><br/>
            <?php if($canEditItem): ?>
                <input type="text" name="item[<?php echo $id ?>][tax_percent]"
                   title="<?php echo __("Tax Percent") ?>"
                   class="edit_order_item small required-entry validate-number"
                   value="<?php echo $block->getPercent('tax_percent'); ?>"/>
            <?php endif; ?>
        <?php endif; ?>
    </td>


    <?php /** DISCOUNT AMOUNT **/ ?>
    <td class="col-discount">
        <?php if ($canShowPriceInfo): ?>
            <input type="hidden" value="<?php echo $block->getPrice('base_discount_amount'); ?>" name="item[<?php echo $id ?>][discount_amount]"/>
        <?php else: ?>
            <?php echo $block->getPriceHtml('base_discount_amount') ?>
            <?php if($canEditItem): ?>
                <input type="text" name="item[<?php echo $id ?>][discount_amount]" readonly="readonly"
                   title="<?php echo __("Discount amount") ?>"
                   class="edit_order_item small required-entry validate-number readonly"
                   value="<?php echo $block->getPrice('base_discount_amount'); ?>"/>
            <?php endif; ?>
        <?php endif; ?>
    </td>


    <?php /** DISCOUNT PERCENT **/ ?>
    <td class="col-discount-percent">
        <?php if ($canShowPriceInfo): ?>
            <input type="hidden" value="<?php echo $block->getPercent('discount_percent'); ?>" name="item[<?php echo $id ?>][discount_percent]"/>
        <?php else: ?>
            <label><?php echo $block->getPercentHtml('discount_percent') ?></label><br/>
            <?php if($canEditItem): ?>
                <input type="text" name="item[<?php echo $id ?>][discount_percent]"
                   title="<?php echo __("Discount percent") ?>"
                   class="edit_order_item small required-entry validate-number"
                   value="<?php echo $block->getPercent('discount_percent'); ?>"/>
            <?php endif; ?>
        <?php endif; ?>
    </td>


    <?php /** TOTAL **/ ?>
    <td class="col-total">
        <?php if ($canShowPriceInfo): ?>
            <input type="hidden" value="<?php echo $block->getBaseItemTotal(); ?>" name="item[<?php echo $id; ?>][row_total]"/>
        <?php else: ?>
            <label><b><?php echo $block->getItemTotalHtml() ?></b></label><br/>
            <?php if($canEditItem): ?>
                <input type="text" name="item[<?php echo $id ?>][row_total]" readonly="readonly"
                   title="<?php echo __("Total") ?>"
                   class="edit_order_item small required-entry validate-number readonly"
                   value="<?php echo $block->getBaseItemTotal(); ?>"/>
            <?php endif; ?>
        <?php endif; ?>
    </td>


    <?php /** REMOVE **/ ?>
    <td class="ordered_item_remove a-center last">
        <?php if($type == 'quote'): ?>
            <span <?php if($hasParent): ?>data-parent-id="<?php echo $parentId ?>"<?php endif; ?>
                  data-id="<?php echo $id ?>" class="remove_quote_item">
                <i class="fa fa-times"></i>
            </span>
        <?php elseif($item->getQtyRefunded() != $item->getQtyOrdered() && $canDeleteItem): ?>
            <div class="action-multicheck-wrap">
                <input type="checkbox" name="item[<?php echo $id ?>][remove]"
                       title="<?php echo __("Remove") ?>"
                       class="remove_ordered_item <?php if($hasParent): ?>has-parent<?php endif; ?>"
                       <?php if($hasParent): ?>data-parent-id="<?php echo $parentId ?>"<?php endif; ?>
                       data-item-id="<?php echo $id ?>"
                       id="remove_<?php echo $id ?>" value="1"/>
                <label for="remove_<?php echo $id ?>"></label>
            </div>
        <?php endif; ?>

        <?php /** ADDITIONAL PARAMS **/ ?>
        <input type="hidden" class="edit_order_item"
               value="<?php echo $item->getProductId() ?>"
               name="item[<?php echo $id ?>][product_id]"/>
        <input type="hidden" class="edit_order_item"
               value="<?php echo $block->getPrice('weee_tax_applied_row_amount'); ?>"
               name="item[<?php echo $id ?>][weee_tax_applied_row_amount]"/>
        <input type="hidden" class="edit_order_item"
               value="<?php echo $block->getPrice('discount_tax_compensation_amount'); ?>"
               name="item[<?php echo $id ?>][discount_tax_compensation_amount]"/>
        <input type="hidden"
               value="<?php echo $type ?>"
               name="item[<?php echo $id ?>][item_type]"/>
        <input type="hidden"
               value="<?php echo $item->getId() ?>"
               name="item[<?php echo $id ?>][item_id]"/>
    </td>
</tr>
