<?php
$quote = $block->getCheckoutSession()->getQuote();
$_dataHelper = $this->helper('MW\RewardPoints\Helper\Data');
$amount = $quote->getMwRewardpointDiscountShow();

if ($amount != 0) :
	$point = $quote->getMwRewardpoint();
	$pointShow = $_dataHelper->formatPoints($point);
?>
	<tr>
	    <th colspan="<?php echo $this->getColumnSpan() ?>" scope="row" class="mark"><?php echo __("You Redeem (%1)", $pointShow) ?></th>
	    <td class="amount">
	        <span class="price"><?php echo $_dataHelper->formatMoney(-$amount, true, false); ?></span>
		</td>
	</tr>
<?php endif; ?>