<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/* @var $block \Aheadworks\Rma\Block\CustomField\Input\Renderer\Text */
?>
<?php
    $isWrapped = $block->getIsWrapped();
    $isRequired = $block->isRequired();
    $fieldClasses = 'field aw-rma-custom-field';
    if ($isRequired) {
        $fieldClasses .= ' required';
    }
    $labelClasses = 'label';
    if ($isRequired) {
        $labelClasses .= ' required';
    }
?>
<?php if ($isWrapped): ?>
    <div class="<?php echo $fieldClasses ?>">
        <label class="<?php echo $labelClasses ?>" for="<?php echo $block->getHtmlId() ?>"><span><?php echo $block->getCustomField()->getFrontendLabel() ?></span></label>
        <div class="control">
<?php endif; ?>
        <?php if ($block->isEditable()): ?>
            <input id="<?php echo $block->getHtmlId() ?>"
                   name="<?php echo $block->getName() ?>"
                   type="text"
                   class="<?php echo $block->getCssClass() ?>"
                   value="<?php echo $block->escapeHtml($block->getValue()) ?>"
                   data-id="<?php echo $block->getCustomField()->getId() ?>"
                />
        <?php else: ?>
            <span><?php echo $block->getValue() ?></span>
        <?php endif; ?>
<?php if ($isWrapped): ?>
        </div>
    </div>
<?php endif; ?>
