<div class="b2b-modal fade iwdsr-customers-list-modal" id="iwdsr-customers-list-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="b2b-modal-dialog">
        <div class="b2b-modal-content">
            <div class="b2b-modal-body">
                <a class="close" data-dismiss="modal">
                    <i class="fa fa-times customer-close" aria-hidden="true"></i>
                </a>
                <div class="iwdsr-customers-list-wrap"></div>
            </div>
            <div class="b2b-modal-footer">
            </div>
        </div>
    </div>
</div>
