<?php
/**
 * @var $block IWD\MultiInventory\Block\Adminhtml\Warehouses\Jsinit
 */
?>

<script type="text/javascript">
    // <![CDATA[
    require([
            "IWD_MultiInventory/js/creditmemo/view/info",
            "prototype"
        ],
        function(iwdMultiInventoryCreditmemoInfo) {
            var multiInventoryCreditmemoInfo = new iwdMultiInventoryCreditmemoInfo();
            multiInventoryCreditmemoInfo.init(<?php echo $block->jsonParamsCreditmemoInfo(); ?>);
        }
    );
    // ]]>
</script>