<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_CustomerAttributes
 */
?>
<div class="admin__page-section-title <?php /* @escapeNotVerified */ echo $block->getHeaderCssClass() ?>">
    <span class="title"><?php /* @escapeNotVerified */ echo $block->getHeaderText() ?></span>
    <div class="actions"></div>
</div>
<div id="customer_account_fieds" class="admin__page-section-content">
    <?php echo 'die' ?>
</div>