<?php
/**
 * @var $block IWD\MultiInventory\Block\Adminhtml\Order\Items\Stock\Renderer
 */

$item = $block->getItem();
$id = $item->getItemId();
$type = $item->getProductType();

if ($type == 'configurable') {
    $childItems = $item->getChildrenItems();
    if (isset($childItems[0])) {
        $item = $childItems[0];
        $id = $item->getItemId();
    }
}
?>

<div id="assign_stock_<?php echo $block->escapeHtml($id) ?>"></div>