<?php
$_dataHelper = $this->helper('MW\RewardPoints\Helper\Data');
$quote = $block->_getQuote();
$spend_point = $block->getMaxPointsToCheckout();
$earnRewardPoint = (int)$quote->getEarnRewardpoint();
$reward_icon = $_dataHelper->getRewardIconHtml();
$rate = $block->getPointPerMoney();
?>
<div id="rewardpoints_box" style="width: 100%; margin-bottom: 15px;">
    <form id="rewardpoints-form" action="<?php echo $block->getUrl('rewardpoints/checkout/rewardPointsPost') ?>"  onsubmit="return false;" method="post">
        <div class="discount discount-codes box" style="width: 90%; padding: 20px; background: none repeat scroll 0 0 #F5F5F5;">
        	<div style="background-image: : none; padding: 0px;"><?php echo $reward_icon ?><label style="color: #666666;font-weight: bold;" for="mw_amount"><?php echo __('Points to redeem')?> </label><input style="color:#f6931f; width:50px; text-align:center;font-size: 13px;font-weight: bold;" type="text" name="mw_amount" id="mw_amount" /> <label id="mw_label_amount" style="color:#f6931f; font-weight:bold;display:none;"></label></div>

            <div class="discount-form">
                <div style="width:100%; padding-top: 5px;">
                    <?php if ($block->_getCustomer()->getId()) : ?>
                        <div style="float:left;width:258px; border-top: 1px dashed;">
                            <div id="mw_reward_slider_contaner" class="mw_reward_slider_contaner" style="width:215px;">
                                <div id="mw_reward_decr_handle"></div>
                                <div id="mw_reward_incr_handle"></div>
                                <div id="mw_slider" class="mw_reward_select"></div>
                            </div>
                            <div style="margin-top: 10px;">
                                <input type="checkbox" name="mw_use_max_points" id="mw_use_max_points" />
                                <label for="mw_use_max_points" style="padding-left: 5px;"><?php echo __("Use maximum (<b>%1</b>)",$_dataHelper->formatPoints($spend_point));?></label>
                            </div>
                        </div>
                    <?php else: ?>
                        <div style="text-align: center; margin-top:10px; border-top: 1px dashed;padding-top: 10px;">
                            <?php echo __("Please <a href='%1'>LOGIN</a> to use reward points", $block->getUrl('customer/account/login', ['mw_re_login' => 1]))?>
                        </div>
                    <?php endif; ?>
                </div>

                <div style="clear:both;"></div>
            </div>
        </div>
    </form>
</div>

<?php
$point = $quote->getMwRewardpoint();
$step = $_dataHelper->getPointStepConfig();
$min = (int) $_dataHelper->getMinPointCheckoutStore();
?>

<script>
	require([
		'jquery',
		'mwRewardSlider'
	], function($) {
		$('body').on('click', '#mw_view', function() {
			var mw_view = $(this);
			$('#reward-points-rules').slideToggle(400, function() {
				if (mw_view.text() == '<?php echo __("(Hide)");?>') {
					mw_view.text('<?php echo __("(Details)");?>');
				} else {
					mw_view.text('<?php echo __("(Hide)");?>');
				}
			});

			return false;
		});

		<?php if ($block->_getCustomer()->getId()) : ?>
		// Reward Points Slider
		var mw_time = 1000;
		var mw_time_new = 2000;
		var mw_timer;
		var mw_sider = new MwRewardSlider(
			'mw_amount',
			'mw_reward_slider_contaner',
			'mw_slider',
			'mw_reward_decr_handle',
			'mw_reward_incr_handle',
			<?php echo $min ?>,
			<?php echo $block->getMaxPointsToCheckout() ?>,
			<?php echo $step ?>,
			'mw_label_amount',
			'mw_use_max_points'
		);

		mw_sider.setPointChange(<?php echo $point ?>);
		mw_sider.changeRewardPointCallback = runTimer;

		$('body').on('change', '#mw_amount', function() {
			var mw_amount = $(this).val();
			clearTimeout(mw_timer);
			mw_timer = setTimeout(mw_sider.setPointChange(mw_amount), mw_time_new);
		});

		$('body').on('click', '#mw_use_max_points', function() {
			if ($(this).is(':checked')) {
				mw_sider.setPointChange(<?php echo $block->getMaxPointsToCheckout()?>);
			} else {
				mw_sider.setPointChange(0);
			}
		});

		function runTimer() {
			clearTimeout(mw_timer);
			mw_timer = setTimeout("gb_view_onestep_plugin_rewardpoints.updateRewardPoints(<?php echo $step ?>, <?php echo $min ?>);", mw_time);
		}
		<?php endif; ?>
	});
</script>