<?php
$quote = $block->getCheckoutSession()->getQuote();
$rewardpoints = $quote->getMwRewardpoint();
$rewardpointSellProduct = (int) $quote->getMwRewardpointSellProduct();
$totalRewardpoints = $rewardpoints + $rewardpointSellProduct;
?>
<?php if ($totalRewardpoints && $rewardpointSellProduct) : ?>
<tr>
    <th colspan="1" scope="row" class="mark"><?php echo __('Total Points') ?></th>
    <td class="amount">
        <span class="price"><?php echo $this->helper('MW\RewardPoints\Helper\Data')->formatPoints($totalRewardpoints) ?></span>
	</td>
</tr>
<?php endif; ?>
